### ISSUE TITLE
Network is unreachable error

### ISSUE THREAD

**Issue by marangiop** [qubvel/segmentation_models#121]
Hello, it seemed to work fine at the beginning but I am now getting the same error all the time. I have tried both types of installations (pip install segmentation-models or pip install git+https://github.com/qubvel/segmentation_models) but didn't make a difference 

2019-06-09 17:35:33.180264: I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/site-packages/keras/utils/data_utils.py", line 222, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 33, in <module>
    model = Unet(BACKBONE, encoder_weights='imagenet')
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/site-packages/segmentation_models/utils.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/site-packages/segmentation_models/unet/model.py", line 62, in Unet
    include_top=False)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/site-packages/segmentation_models/backbones/__init__.py", line 100, in get_backbone
    return Classifiers.get_classifier(name)(*args, **kwargs)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/site-packages/classification_models/resnet/models.py", line 25, in classifier
    load_model_weights(weights_collection, model, weights, classes, include_top)
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/site-packages/classification_models/utils.py", line 24, in load_model_weights
    md5_hash=weights['md5'])
  File "/lustre/home/d167/s1137563/ENTER/lib/python3.7/site-packages/keras/utils/data_utils.py", line 226, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://github.com/qubvel/classification_models/releases/download/0.0.1/resnet18_imagenet_1000_no_top.h5: None -- [Errno 101] Network is unreachable

Not sure why I am getting these errors...

**Comment by qubvel** [comment]
Some problems with connection to github, not an issue.
try one more time, use vpn
