### ISSUE TITLE
custom loss issue

### ISSUE THREAD

**Issue by srikrishna0130** [qubvel/segmentation_models#141]
I am facing a problem with using a custom metric function to compile the model.
My custom function is as follows:
```python
def mean_iou(y_true, y_pred):
    prec = []
    for t in np.arange(0.5, 1.0, 0.05):
        y_pred_ = tf.to_int32(y_pred > t)
        score, up_opt = tf.metrics.mean_iou(y_true, y_pred_, 2)
        K.get_session().run(tf.global_variables_initializer())
        K.get_session().run(tf.local_variables_initializer())
        with tf.control_dependencies([up_opt]):
            score = tf.identity(score)
        prec.append(score)
    return K.mean(K.stack(prec), axis=0)
```
And i used the custom metric here :
```python
earlystopper = EarlyStopping(patience=4, verbose=1)
checkpointer = ModelCheckpoint(args.model, verbose=1, save_best_only=True)
results = model.fit(x_train, y_train, validation_split=0.1, batch_size=20, epochs=10, 
                callbacks=[earlystopper, checkpointer])
```
I get the following error message
```
Traceback (most recent call last):
  File "unet_resnet_model.py", line 151, in <module>
    main()
  File "unet_resnet_model.py", line 138, in main
    model.fit(x_train, y_train, epochs = 1)
  File "/home/potnurch/.conda/envs/tf_chait/lib/python3.6/site-packages/keras/engine/training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "/home/potnurch/.conda/envs/tf_chait/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "/home/potnurch/.conda/envs/tf_chait/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/potnurch/.conda/envs/tf_chait/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/potnurch/.conda/envs/tf_chait/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/potnurch/.conda/envs/tf_chait/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value metrics/iou/mean_iou/total_confusion_matrix
         [[{{node metrics/iou/mean_iou/total_confusion_matrix/read}} = Identity[T=DT_DOUBLE, _class=["loc:@metrics/iou/mean_iou/AssignAdd"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](metrics/iou/mean_iou/total_confusion_matrix)]]
```
I have initialized both global and local variables in the custom metric function.
Can you please help me?

Thank you in advance.

**Comment by qubvel** [comment]
Hi @srikrishna0130 
Cannot answer your question, try to find implementation on kaggle.com
AFAIR salt identification challenge have such metric

**Comment by srikrishna0130** [comment]
hi @qubvel , 
I have earlier tried the same custom metric function on a plain u-net model built using tf.keras, and it works fine.
Any idea why it is showing the exception for this particular case?

Sorry if I made any mistake I am relatively new to this.

**Comment by qubvel** [comment]
I think keras make all session/variable "magic" inside, so may be in your function you can just use tf.<ops> without any initialization?
