### ISSUE TITLE
An existing connection was forcibly closed by the remote host for imagenet

### ISSUE THREAD

**Issue by uceshaf** [qubvel/segmentation_models#145]
Hi,
I am trying to test the U-net with resnet34 as backbone on chips of Planet imagery. It is a 4-band imagery so I have tried both methods. Only the method of specifying encoder_weights=None works but when I specify encoder_weights='imagenet' after doing 
``` 1 = Conv2D(3, (1, 1))(inp) # map N channels data to 3 channels ```
I get the following error after the code runs for a while.
```
Traceback (most recent call last):
  File "PlanetSampleModelPrepSegmentationModels.py", line 64, in <module>
    base_model = Unet(backbone_name=BACKBONE, encoder_weights='imagenet')
  File "C:\Program Files\Python36\lib\site-packages\segmentation_models\utils.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\segmentation_models\unet\model.py", line 63, in Unet
    include_top=False)
  File "C:\Program Files\Python36\lib\site-packages\segmentation_models\backbones\__init__.py", line 75, in get_backbone
    return Classifiers.get_classifier(name)(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\classification_models\resnet\models.py", line 25, in classifier
    load_model_weights(weights_collection, model, weights, classes, include_top)
  File "C:\Program Files\Python36\lib\site-packages\classification_models\utils.py", line 24, in load_model_weights
    md5_hash=weights['md5'])
  File "C:\Program Files\Python36\lib\site-packages\keras\utils\data_utils.py", line 222, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 277, in urlretrieve
    block = fp.read(bs)
  File "C:\Program Files\Python36\lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "C:\Program Files\Python36\lib\http\client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "C:\Program Files\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\Python36\lib\ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\Python36\lib\ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "C:\Program Files\Python36\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```
How do I stop the connection from resetting. I want to use the imagenet weights and can not afford to train the model from default on my full dataset as it is quite big.

Thanks for any help in this regard.

**Comment by qubvel** [comment]
I don`t think it is a relevant issue, make sure internet connection work fine to load weights.
Anyway, you can try to load weight from releases, and put them to `~/.keras/models/` dir.
