### ISSUE TITLE
ValueError: You are trying to load a weight file containing 428 layers into a model with 114 layers.

### ISSUE THREAD

**Issue by zhudaoruyi** [qubvel/segmentation_models#153]
I have trained a segmentation model, the backbone is densenet201 with pretrained model, the decoder is FPN
But, when I load saved weight for predicting,raise error as below:

```bash
Traceback (most recent call last):
  File "test.py", line 62, in <module>
    main()
  File "test.py", line 57, in main
    apply_predict()
  File "test.py", line 27, in apply_predict
    model.load_weights("models/densenet201_fpn_w.h5")
  File "/home/jiangd/.conda/envs/tf110/lib/python3.5/site-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/jiangd/.conda/envs/tf110/lib/python3.5/site-packages/keras/engine/saving.py", line 1030, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 428 layers into a model with 114 layers.
```

**Comment by zhudaoruyi** [comment]
When I load saved model h5 file, raise error as below:

```bash
  File "test.py", line 28, in apply_predict
    model = load_model("models/densenet201_fpn_m.h5")
  File "/home/jiangd/.conda/envs/tf110/lib/python3.5/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/jiangd/.conda/envs/tf110/lib/python3.5/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/jiangd/.conda/envs/tf110/lib/python3.5/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/jiangd/.conda/envs/tf110/lib/python3.5/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/jiangd/.conda/envs/tf110/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/jiangd/.conda/envs/tf110/lib/python3.5/site-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "/home/jiangd/.conda/envs/tf110/lib/python3.5/site-packages/keras/engine/network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "/home/jiangd/.conda/envs/tf110/lib/python3.5/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/jiangd/.conda/envs/tf110/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: ResizeImage
```

**Comment by zhudaoruyi** [comment]
```bash
(tf110) [jiangd@ibmu01 code]$ conda list
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at /home/jiangd/.conda/envs/tf110:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_tflow_select             2.1.0                       gpu  
absl-py                   0.4.1                    py35_0  
astor                     0.7.1                    py35_0  
backcall                  0.1.0                    py35_0  
backports                 1.0                        py_2  
backports.weakref         1.0rc1                   py35_0  
blas                      1.0                         mkl  
bleach                    1.5.0                    py35_0  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2019.5.15                     0  
cairo                     1.14.12              h8948797_3  
certifi                   2018.8.24                py35_1  
cudatoolkit               8.0                           3  
cudnn                     7.1.3                 cuda8.0_0  
cupti                     8.0.61                        0  
cycler                    0.10.0           py35hc4d5149_0  
dbus                      1.13.6               h746ee38_0  
decorator                 4.4.0                      py_0  
defusedxml                0.6.0                      py_0  
efficientnet              0.0.4                    pypi_0    pypi
entrypoints               0.2.3                    py35_2  
expat                     2.2.6                he6710b0_0  
ffmpeg                    4.0                  hcdf2ecd_0  
fontconfig                2.13.0               h9420a91_0  
freeglut                  3.0.0                hf484d3e_5  
freetype                  2.9.1                h8a8886c_1  
gast                      0.2.0                    py35_0  
glib                      2.56.2               hd408876_0  
gmp                       6.1.2                h6c8ec71_1  
graphite2                 1.3.13               h23475e2_0  
grpcio                    1.12.1           py35hdbcaa40_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.8.0            py35h989c5e5_3  
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.2               hba1933b_1  
html5lib                  0.9999999                py35_0  
icu                       58.2                 h9c2bf20_1  
image-classifiers         0.2.0                    pypi_0    pypi
imageio                   2.5.0                    pypi_0    pypi
intel-openmp              2019.4                      243  
ipykernel                 4.10.0                   py35_0  
ipython                   6.5.0                    py35_0  
ipython_genutils          0.2.0            py35hc9e07d0_0  
jasper                    2.0.14               h07fcdf6_1  
jedi                      0.12.1                   py35_0  
jinja2                    2.10                     py35_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0            py35h4395190_0  
jupyter_client            5.2.3                    py35_0  
jupyter_core              4.5.0                      py_0  
keras                     2.1.2                    pypi_0    pypi
keras-applications        1.0.7                    pypi_0    pypi
keras-preprocessing       1.0.9                    pypi_0    pypi
kiwisolver                1.0.1            py35hf484d3e_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libglu                    9.0.0                hf484d3e_1  
libopencv                 3.4.2                hb342d67_1  
libopus                   1.3                  h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.6.0                hdbcaa40_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10               h2733197_2  
libuuid                   1.0.3                h1bed415_2  
libvpx                    1.7.0                h439df22_0  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                hea5a465_1  
markdown                  2.6.11                   py35_0  
markupsafe                1.0              py35h14c3975_1  
matplotlib                3.0.3                    pypi_0    pypi
mistune                   0.8.3            py35h14c3975_1  
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6            py35h7dd41cf_0  
mkl_random                1.0.1            py35h4414c95_1  
nbconvert                 5.5.0                      py_0  
nbformat                  4.4.0            py35h12e6e07_0  
ncurses                   6.1                  he6710b0_1  
networkx                  2.3                      pypi_0    pypi
notebook                  5.6.0                    py35_0  
numpy                     1.15.2           py35h1d66e8a_0  
numpy-base                1.15.2           py35h81de0dd_0  
olefile                   0.46                     py35_0  
opencv                    3.4.2            py35h6fd60c2_1  
openssl                   1.0.2s               h7b6447c_0  
pandas                    0.23.4           py35h04863e7_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py35_1  
parso                     0.5.0                      py_0  
pcre                      8.43                 he6710b0_0  
pexpect                   4.6.0                    py35_0  
pickleshare               0.7.4            py35hd57304d_0  
pillow                    5.2.0            py35heded4f4_0  
pip                       10.0.1                   py35_0  
pixman                    0.38.0               h7b6447c_0  
prettytable               0.7.2                    pypi_0    pypi
prometheus_client         0.7.1                      py_0  
prompt_toolkit            1.0.15           py35hc09de7a_0  
protobuf                  3.6.0            py35hf484d3e_0  
ptyprocess                0.6.0                    py35_0  
py-opencv                 3.4.2            py35hb342d67_1  
pygments                  2.4.2                      py_0  
pyparsing                 2.4.0                      py_0  
pyqt                      5.9.2            py35h05f1152_2  
python                    3.5.6                hc3d631a_0  
python-dateutil           2.7.3                    py35_0  
pytz                      2019.1                     py_0  
pywavelets                1.0.3                    pypi_0    pypi
pyyaml                    3.13             py35h14c3975_0  
pyzmq                     17.1.2           py35h14c3975_0  
qt                        5.9.6                h8703b6f_2  
readline                  7.0                  h7b6447c_5  
scikit-image              0.15.0                   pypi_0    pypi
scikit-learn              0.20.0           py35h4989274_1  
scipy                     1.1.0            py35hfa4b5c9_1  
segmentation-models       0.2.1                    pypi_0    pypi
send2trash                1.5.0                    py35_0  
setuptools                40.2.0                   py35_0  
simplegeneric             0.8.1                    py35_2  
sip                       4.19.8           py35hf484d3e_0  
six                       1.11.0                   py35_1  
sqlite                    3.28.0               h7b6447c_0  
tensorboard               1.10.0           py35hf484d3e_0  
tensorflow                1.10.0          gpu_py35ha6119f3_0  
tensorflow-base           1.10.0          gpu_py35h3435052_0  
tensorflow-gpu            1.10.0               hf154084_0  
tensorflow-gpu-base       1.7.0            py35h5b7bae4_1  
termcolor                 1.1.0                    py35_1  
terminado                 0.8.1                    py35_1  
testpath                  0.3.1            py35had42eaf_0  
tk                        8.6.8                hbc83047_0  
tornado                   5.1.1            py35h7b6447c_0  
tqdm                      4.32.1                     py_0  
traitlets                 4.3.2            py35ha522a97_0  
wcwidth                   0.1.7            py35hcd08066_0  
werkzeug                  0.15.4                     py_0  
wheel                     0.31.1                   py35_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.2.5                hf484d3e_1  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  
```

**Comment by qubvel** [comment]
Hi @zhudaoruyi 
Did you use master branch or PyPI package?

**Comment by zhudaoruyi** [comment]
I installed by this command

```bash
pip install segmentation-models
```

**Comment by qubvel** [comment]
To load model use:
```python
import segmentation_models # important!
from keras.models import load_model

model = load_model('path/model.h5')
```
Hope this helps.

**Comment by zhudaoruyi** [comment]
`load_model` worked with adding `import segmentation_models` , thks

**Comment by zhudaoruyi** [comment]
You have done a very nice job, and can you do something more,  such as adding predict demo, postprocessing demo ?

**Comment by zhudaoruyi** [comment]
and deeplabv3+

**Comment by qubvel** [comment]
Now I am working on adopting all models for `tf.keras` (you can check in tf.keras branch), after that I am going to make some tutorials with training/inference

**Comment by qubvel** [comment]
afaik, deeplbv3+ use dilated convs in encoder, so may be it will be not so easy to put it here.

**Comment by qubvel** [comment]
`focal loss` and `lovasz`  also in plans
