### ISSUE TITLE
Problem using a b5 backbone with unet

### ISSUE THREAD

**Issue by bfialkoff** [qubvel/segmentation_models#155]
The following code crashes:

```
model = Unet(backbone_name='efficientnetb5', classes=4, encoder_weights='imagenet',
                         input_shape=(456, 456, 3))
```
I also tried 
`model = Unet(backbone_name='efficientnetb5', classes=4, encoder_weights='imagenet')`

Both result in the following error:
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 30, 30, 2048), (None, 29, 29, 1056)]

Full stacktrace:
Traceback (most recent call last):
  File "/home/adam/Desktop/bud_classes/train_model.py", line 54, in <module>
    input_shape=(input_size, input_size, 3))
  File "/home/adam/.local/lib/python3.6/site-packages/segmentation_models/utils.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/adam/.local/lib/python3.6/site-packages/segmentation_models/unet/model.py", line 75, in Unet
    use_batchnorm=decoder_use_batchnorm)
  File "/home/adam/.local/lib/python3.6/site-packages/segmentation_models/unet/builder.py", line 40, in build_unet
    skip=skip_connection, use_batchnorm=use_batchnorm)(x)
  File "/home/adam/.local/lib/python3.6/site-packages/segmentation_models/unet/blocks.py", line 37, in layer
    x = Concatenate()([x, skip])
  File "/home/adam/.local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/adam/.local/lib/python3.6/site-packages/keras/layers/merge.py", line 362, in build
    'Got inputs shapes: %s' % (input_shape))
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 30, 30, 2048), (None, 29, 29, 1056)]

**Comment by qubvel** [comment]
Hi this is not `efficientnetb5` issue, input_shape `h` nad `w` should be divisible by 32.

**Comment by bfialkoff** [comment]
The efficientnetb5 imagenet weights are for input_shape 456, so if we want to use the b5 as a backbone then we cant use the imagenet weights. Is that correct?

**Comment by qubvel** [comment]
No, for segmentation models you can use it, because weights loaded only for convolution layers (not for dense).

**Comment by qubvel** [comment]
Set other shape:
```python
model = Unet(
    backbone_name='efficientnetb5', 
    classes=4, 
    encoder_weights='imagenet',
    input_shape=(442, 442, 3),
)
```

Or do not specifiy shape, BUT provide images with shape divisible by 32:
```python
model = Unet(
    backbone_name='efficientnetb5', 
    classes=4, 
    encoder_weights='imagenet',
)
```

**Comment by bfialkoff** [comment]
Amazing! Thank you! I'll try it out
