### ISSUE TITLE
How can I use the mode pspnet?

### ISSUE THREAD

**Issue by MaxKinny** [qubvel/segmentation_models#16]
I executed the code:
```
from segmentation_models import pspnet
model = pspnet(backbone_name='inceptionresnetv2', freeze_encoder=True, input_shape=(None, None, 3))
```
But the console returned the error as follow:
```
Traceback (most recent call last):
  File "/home/[UserName]/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-4764359b8965>", line 1, in <module>
    model = pspnet(freeze_encoder=True, input_shape=(None, None, 3))
TypeError: 'module' object is not callable
```
What would be the problem?

**Comment by qubvel** [comment]
@MaxKinny  try `from segmentation_models import PSPNet`

**Comment by MaxKinny** [comment]
> @MaxKinny try `from segmentation_models import PSPNet`

Thank You, the problem has been solved.
