### ISSUE TITLE
How to convert 5 channel to 3? 

### ISSUE THREAD

**Issue by frankdeepl** [qubvel/segmentation_models#225]
Hi guys,
I faced the problem is that when I do prediction I got (1, 256, 1600, 5) image. I tried to do 4 classed segmentation. 

```
2019-10-14 10:49:40.385612: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
<class 'numpy.ndarray'>
(1, 256, 1600, 5)
Backend TkAgg is interactive backend. Turning interactive mode on.
<class 'numpy.ndarray'>
(256, 1600, 5)
Traceback (most recent call last):
  File "/home/dongs/Documents/Software/pycharm-community-2019.1.2/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/home/dongs/Documents/Software/pycharm-community-2019.1.2/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/dongs/Documents/Software/pycharm-community-2019.1.2/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/dongs/Documents/Software/pycharm-community-2019.1.2/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/dongs/Documents/Project/Kaggle/severstal-steel-defect-detection/segmentation_models-master/examples/test_keras.py", line 51, in <module>
    cv2.imwrite(dst, pr_mask)
cv2.error: OpenCV(4.1.1) /io/opencv/modules/imgcodecs/src/loadsave.cpp:667: error: (-215:Assertion failed) image.channels() == 1 || image.channels() == 3 || image.channels() == 4 in function 'imwrite_' 
```

I don't know what is wrong with my code, how can I resolve this problem?

**Comment by JordanMakesMaps** [comment]
So (1, 256, 1600, 5) is the shape, where you have (batch size, height, width, channels). It looks like you're trying to save a file with CV2 using `imwrite()`. Because there are 5 channels it doesn't know what to do with that extra one, that's why you're getting that error.

If you want to just __see__ the predictions, you can do `np.argmax(prediction, axis = 2)` which will give you a 1-channel mask showing the predictions for each pixel. If you're trying to __save__ the predictions so you can use them in another application, I recommend using `np.save()`, then to open them us `np.load()`

**Comment by frankdeepl** [comment]
Hi @JordanMakesMaps ,

Thanks for your help. :)
I have found anther way to resolve this problem which is same as your solution. 
I tried to use` np.argmax(prediction, axis = 3)`, and then reshape it to (256, 1600, 1).   

But I think your method is better than me. 

Thanks again.
