### ISSUE TITLE
dice_loss and NumPy 1.17.3

### ISSUE THREAD

**Issue by Daemon2017** [qubvel/segmentation_models#240]
Hello!

Loss-function dice_loss works fine with NumPy 1.15.4, but with last version (1.17.3) I'm getting error:
`C:\Users\Daemon\AppData\Local\Programs\Python\Python35\python.exe C:/Users/Daemon/PycharmProjects/atDNARelationshipDetector/train.py
C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\segmentation_models\__init__.py", line 98, in <module>
    set_framework(_framework)
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\segmentation_models\__init__.py", line 68, in set_framework
    import efficientnet.keras  # init custom objects
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\efficientnet\keras.py", line 4, in <module>
    from .preprocessing import center_crop_and_resize
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\efficientnet\preprocessing.py", line 16, in <module>
    from skimage.transform import resize
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\skimage\__init__.py", line 158, in <module>
    from .util.dtype import *
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\skimage\util\__init__.py", line 7, in <module>
    from .arraycrop import crop
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\skimage\util\arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Daemon/PycharmProjects/atDNARelationshipDetector/train.py", line 5, in <module>
    from generators import batch_test_generator, batch_train_generator, size_of_batch
  File "C:\Users\Daemon\PycharmProjects\atDNARelationshipDetector\generators.py", line 5, in <module>
    from mymodel import matrix_width, matrix_height, classes
  File "C:\Users\Daemon\PycharmProjects\atDNARelationshipDetector\mymodel.py", line 7, in <module>
    from segmentation_models.losses import dice_loss
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\segmentation_models\__init__.py", line 101, in <module>
    set_framework(other)
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\segmentation_models\__init__.py", line 71, in set_framework
    import efficientnet.tfkeras  # init custom objects
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\efficientnet\tfkeras.py", line 4, in <module>
    from .preprocessing import center_crop_and_resize
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\efficientnet\preprocessing.py", line 16, in <module>
    from skimage.transform import resize
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\skimage\transform\__init__.py", line 1, in <module>
    from .hough_transform import (hough_line, hough_line_peaks,
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\skimage\transform\hough_transform.py", line 3, in <module>
    from .. import measure
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\skimage\measure\__init__.py", line 2, in <module>
    from ._marching_cubes_lewiner import marching_cubes, marching_cubes_lewiner
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\skimage\measure\_marching_cubes_lewiner.py", line 17, in <module>
    from .._shared.utils import skimage_deprecation, warn
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\skimage\_shared\utils.py", line 10, in <module>
    from ..util import img_as_float
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\skimage\util\__init__.py", line 7, in <module>
    from .arraycrop import crop
  File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\skimage\util\arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'`

**Comment by AlpAribal** [comment]
This error occurs because `scikit-image<=0.14.1` depends on the numpy method `_validate_lengths()`, which was removed from numpy as of v1.16.0. This should be fixed with scikit-image v0.14.2. Check [this](https://github.com/numpy/numpy/issues/12744) and [this](https://github.com/scikit-image/scikit-image/issues/3649) for more details.
