### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by asafdar** [qubvel/segmentation_models#248]
Hi, when I try to `import segmentation_models as sm` I get an error:

`cannot import name 'get_submodules_from_kwargs'`

**Comment by asafdar** [comment]
To follow up:

I re-installed the library which fixed that particular issue. However, it seems to have broken keras.

Now when I try and import keras I get:
<img width="589" alt="Screen Shot 2019-11-04 at 3 10 57 PM" src="https://user-images.githubusercontent.com/22178535/68158478-565f6800-ff15-11e9-8613-b4080ecfa6be.png">

**Comment by qubvel** [comment]
Check that versions of keras and keras-applications satisfy requirements

**Comment by asafdar** [comment]
keras --> 2.2.1
keras-applications --> 1.0.8

That should be fine, no?

**Comment by qubvel** [comment]
Yes should be fine. Dont have any ideas, try to use a new environment.

**Comment by RAY9874** [comment]
Hi @asafdar  I have faced the same problem with importing Keras error,  with degrading keras-applications --> 1.0.8 to 1.0.7， the problem fixed and sm works well

**Comment by mdo6180** [comment]
i'm getting the same issue as well when i try to import ResNet34. this line is giving me errors:

from classification_models.tfkeras import Classifiers


terminal output:

Traceback (most recent call last):
  File "service.py", line 9, in <module>
    from classification_models.tfkeras import Classifiers
  File "/home/PROJECTS/domp/xrca_demo/virtualenv/lib/python3.7/site-packages/classification_models/tfkeras.py", line 2, in <module>
    from .models_factory import ModelsFactory
  File "/home/PROJECTS/domp/xrca_demo/virtualenv/lib/python3.7/site-packages/classification_models/models_factory.py", line 4, in <module>
    from .models import resnet as rn
  File "/home/PROJECTS/domp/xrca_demo/virtualenv/lib/python3.7/site-packages/classification_models/models/resnet.py", line 5, in <module>
    from ._common_blocks import ChannelSE
  File "/home/PROJECTS/domp/xrca_demo/virtualenv/lib/python3.7/site-packages/classification_models/models/_common_blocks.py", line 1, in <module>
    from classification_models import get_submodules_from_kwargs
ImportError: cannot import name 'get_submodules_from_kwargs' from 'classification_models' (/home/PROJECTS/domp/xrca_demo/virtualenv/lib/python3.7/site-packages/classification_models/__init__.py)

**Comment by mdo6180** [comment]
Nevermind. I figured out what was wrong. I was using a virtual environment and when I ran my code outside of the virtual environment it ran fine.

**Comment by minaahmed** [comment]
@mdo6180 why it is not possible to run it with virtual environment I have the same issue now?

**Comment by kiflowb777** [comment]
I have the same problem, I try both keras-applications 1.0.8 and 1.0.7.

```python
File "C:\python36\lib\site-packages\classification_models\models_factory.py", line 4, in <module>
    from .models import resnet as rn
  File "C:\python36\lib\site-packages\classification_models\models\resnet.py", line 5, in <module>
    from ._common_blocks import ChannelSE
  File "C:\python36\lib\site-packages\classification_models\models\_common_blocks.py", line 1, in <module>
    from classification_models import get_submodules_from_kwargs
ImportError: cannot import name 'get_submodules_from_kwargs'

Process finished with exit code 1
```

I use TensorFlow 2.4.0 with tf.keras.

**Comment by kiflowb777** [comment]
Now when install module with pip the file: ```"...python\Lib\site-packages\classification_models\__init__.py"``` is empty,

but before that it was:

```python
import keras_applications as ka
from .__version__ import __version__


def get_submodules_from_kwargs(kwargs):
    backend = kwargs.get('backend', ka._KERAS_BACKEND)
    layers = kwargs.get('layers', ka._KERAS_LAYERS)
    models = kwargs.get('models', ka._KERAS_MODELS)
    utils = kwargs.get('utils', ka._KERAS_UTILS)
    return backend, layers, models, utils
```

**Comment by CometManAtGitHub** [comment]
Hi
@kiflowb777 : i added this to __init__.py and it imports without issues. I am using Tensorflow 2.5.0 with Anaconda.
Thanks!
