### ISSUE TITLE
issues in gpu training

### ISSUE THREAD

**Issue by jayayy** [qubvel/segmentation_models#281]
i previously used unet architecture to perform semantic segmentation. now ive tried to enlarge the model size as i have 8 tesla v100s. 

```
model = sm.Unet(BACKBONE, input_shape=(800,800,3), encoder_weights = 'imagenet',
                  classes = 1, encoder_freeze=False, activation='sigmoid', decoder_block_type='transpose',
                  decoder_use_batchnorm=True, decoder_filters=(512,512,512,256,128))
```
Backbone is inception resnet v2. ive used mirroredstrategy as provided by tensorflow.distribute but ive been recieveing the following error. this happens after model.fit() is called.

```
Traceback (most recent call last):
  File "800_unet.py", line 169, in <module>
    callbacks = callbacks_list,
  File "/home/rsa-key-20191223/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 649, in fit
    validation_freq=validation_freq)
  File "/home/rsa-key-20191223/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_distributed.py", line 143, in fit_distributed
    steps_name='steps_per_epoch')
  File "/home/rsa-key-20191223/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 274, in model_iteration
    batch_outs = f(actual_inputs)
  File "/home/rsa-key-20191223/.local/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/home/rsa-key-20191223/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Error while reading resource variable batch_normalization_171/beta/replica_7 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/batch_normalization_171/beta/replica_7/N10tensorflow3VarE does not exist.
         [[{{node replica_7/batch_normalization_171/ReadVariableOp}}]]
         [[IteratorGetNext_7/_20743]]
  (1) Failed precondition: Error while reading resource variable batch_normalization_171/beta/replica_7 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/batch_normalization_171/beta/replica_7/N10tensorflow3VarE does not exist.
         [[{{node replica_7/batch_normalization_171/ReadVariableOp}}]]
0 successful operations.
7 derived errors ignored.


```
attaching the code i am using. any help will be appreciated.
[800_unet.txt](https://github.com/qubvel/segmentation_models/files/4018956/800_unet.txt)

**Comment by jayayy** [comment]
update: i want to do model parallelism instead of data parallelism. for that all the guides i referred to suggested that i initialise different layers on diff gpus. is that possible using your awesome repository?

i am struggling because i want to try it over a larger batch size. currently i can do only 8 at atmost but i want to go around 128, atleast.
