### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by ntelo007** [qubvel/segmentation_models#313]
Hi guys,

thank you for this amazing repository! I created a Multi-Output Model using the Unet ResNet34 architecture as you can see in the following figure:

![image](https://user-images.githubusercontent.com/31326655/77232169-b7739980-6b9f-11ea-8ec5-e686a78b50ca.png)

I am using your total_loss from your example (dice + focal loss). Outputs 1 and 3 have 2 classes while output 2 has 37 classes. When I try to train this model I receive the following error:

`
Traceback (most recent call last):
  File "unet_resnet_mtl.py", line 540, in <module>
    validation_steps=len(valid_dataloader),
  File "C:\Users\...\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\...\lib\site-packages\keras\engine\training.py", line 1658, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\...\lib\site-packages\keras\engine\training_generator.py", line 215, in fit_generator
    class_weight=class_weight)
  File "C:\Users\...\lib\site-packages\keras\engine\training.py", line 1449, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\...\lib\site-packages\keras\backend\tensorflow_backend.py", line 2979, in __call__
    return self._call(inputs)
  File "C:\Users\...\lib\site-packages\keras\backend\tensorflow_backend.py", line 2937, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\...\lib\site-packages\tensorflow\python\client\session.py", line 1458, in __call__
    run_metadata_ptr)

tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [1,16,16,37] vs. [1,256,256,37]
         [[{{node loss/output_task_2_loss/mul}}]]
         [[metrics/f1-score/Mean_1/_2291]]
  (1) Invalid argument: Incompatible shapes: [1,16,16,37] vs. [1,256,256,37]
         [[{{node loss/output_task_2_loss/mul}}]]
0 successful operations.
0 derived errors ignored.
`

Could you help me debug this issue?

Thank you once again!

**Comment by Sphincz** [comment]
I had this error a time ago. I think it was due to the different shape of training and validation datasets. Maybe you are resizing/reshaping in data augmentation options in training but not on validation? Check train_dataloader and valid_dataloader shapes. 
I'm not sure about this also. It was a long time ago like i said.

**Comment by ntelo007** [comment]
I am using mainly the code from the example provided, and I modified it to be able to work on a multi-output model. That means that for my Multi-Output model I have the following Dataset and Dataloader classes:

``` 

class Dataset:    
    CLASSES_task_1 = ['background', 'road']
    CLASSES_task_2 = [str(i) for i in list(range(0, 37))] #just creating 37 classes from 0 to 36
    CLASSES_task_3 = ['background', 'intersection']
    
    def __init__(
            self, 
            images_dir, 
            masks_dir_1,
            masks_dir_2,
            masks_dir_3, 
            classes_1=CLASSES_task_1,
            classes_2=CLASSES_task_2, 
            classes_3=CLASSES_task_3, 
            augmentation=None, 
            preprocessing=None,
    ):
        self.ids = os.listdir(images_dir)
        self.images_fps = [os.path.join(images_dir, image_id) for image_id in self.ids]
        self.masks_fps_task_1 = [os.path.join(masks_dir_1, image_id) for image_id in self.ids]
        self.masks_fps_task_2 = [os.path.join(masks_dir_2, image_id) for image_id in self.ids]
        self.masks_fps_task_3 = [os.path.join(masks_dir_3, image_id) for image_id in self.ids]

        # convert str names to class values on masks
        self.class_values_task_1 = [self.CLASSES_task_1.index(cls.lower()) for cls in classes_1]
        self.class_values_task_2 = [self.CLASSES_task_2.index(cls.lower()) for cls in classes_2]
        self.class_values_task_3 = [self.CLASSES_task_3.index(cls.lower()) for cls in classes_3]
        
        self.augmentation = augmentation
        self.preprocessing = preprocessing
    
    def __getitem__(self, i):
        
        # read data
        image = cv2.imread(self.images_fps[i])
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        mask_from_task_1 = cv2.imread(self.masks_fps_task_1[i], 0)
        mask_from_task_1 = np.where(mask_from_task_1==255, 1, mask_from_task_1)  # mask had only 2 values 0 and 255, we convert 255 to 1
        mask_from_task_2 = cv2.imread(self.masks_fps_task_2[i], 0)
        mask_from_task_3 = cv2.imread(self.masks_fps_task_3[i], 0)
        mask_from_task_3 = np.where(mask_from_task_3==255, 1, mask_from_task_3) # mask had only 2 values 0 and 255, we convert 255 to 1
        
        # extract certain classes from mask (e.g. cars)
        masks_task_1 = [(mask_from_task_1 == v) for v in self.class_values_task_1]
        mask_from_task_1 = np.stack(masks_task_1, axis=-1).astype('float')

        masks_task_2 = [(mask_from_task_2 == v) for v in self.class_values_task_2]
        mask_from_task_2 = np.stack(masks_task_2, axis=-1).astype('float')

        masks_task_3 = [(mask_from_task_3 == v) for v in self.class_values_task_3]
        mask_from_task_3 = np.stack(masks_task_3, axis=-1).astype('float')
        
        # apply augmentations
        if self.augmentation:
            sample = self.augmentation(image=image, mask_1=mask_from_task_1, mask_2=mask_from_task_2, mask_3=mask_from_task_3)
            image, mask_from_task_1, mask_from_task_2, mask_from_task_3 = sample['image'], sample['mask_1'], sample['mask_2'], sample['mask_3']
        
        # apply preprocessing
        if self.preprocessing:
            sample = self.preprocessing(image=image, mask_1=mask_from_task_1, mask_2=mask_from_task_2, mask_3=mask_from_task_3)
            image, mask_from_task_1, mask_from_task_2, mask_from_task_3 = sample['image'], sample['mask_1'], sample['mask_2'], sample['mask_3']

        return image, mask_from_task_1, mask_from_task_2, mask_from_task_3

    def __len__(self):
        return len(self.ids)

class Dataloder(keras.utils.Sequence):
    
    def __init__(self, dataset, batch_size=1, shuffle=False):
        self.dataset = dataset
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.indexes = np.arange(len(dataset))
        self.on_epoch_end()

    def __getitem__(self, i):
        
        # collect batch data
        start = i * self.batch_size
        stop = (i + 1) * self.batch_size
        data = []
        X = Y = []
        X = np.empty([self.batch_size, 256, 256, 3])
        Y1 = Y3 = np.empty([self.batch_size, 256, 256, 2])
        Y2 = np.empty([self.batch_size, 256, 256, 37])

        for j in range(start, stop):
            np.append(X, self.dataset[j][0])
            np.append(Y1, self.dataset[j][1])
            np.append(Y2, self.dataset[j][2])
            np.append(Y3, self.dataset[j][3])

        Y = [Y1, Y2, Y3]   
        batch = (X, Y)
        return batch

    def __len__(self):
        """Denotes the number of batches per epoch"""
        return len(self.indexes) // self.batch_size
    
    def on_epoch_end(self):
        """Callback function to shuffle indexes each epoch"""
        if self.shuffle:
            self.indexes = np.random.permutation(self.indexes)
```

Do you see anything weird?

**Comment by Sphincz** [comment]
Yea the shapes are fine. 
Are you using augmentation like the example? There is a random crop on training to 320x320 shape and a padding on validation augmentation.

**Comment by ntelo007** [comment]
I only use the preprocessing functionality.

**Comment by Sphincz** [comment]
Check for reshapes. Check val dataset dimensions. It got to be somewhere. it's a 256x256 vs 16x16.

**Comment by ntelo007** [comment]
I used the following code to make sure all the shapes are kept:

``` 
# Check shapes for errors
assert train_dataloader[0][0].shape == (BATCH_SIZE, 256, 256, 3)
assert train_dataloader[0][1][0].shape == (BATCH_SIZE, 256, 256, n_classes_task_1)
assert train_dataloader[0][1][1].shape == (BATCH_SIZE, 256, 256, n_classes_task_2)
assert train_dataloader[0][1][2].shape == (BATCH_SIZE, 256, 256, n_classes_task_3)

assert valid_dataloader[0][0].shape == (1, 256, 256, 3)
assert valid_dataloader[0][1][0].shape == (1, 256, 256, n_classes_task_1)
assert valid_dataloader[0][1][1].shape == (1, 256, 256, n_classes_task_2)
assert valid_dataloader[0][1][2].shape == (1, 256, 256, n_classes_task_3)
```

No error showed and execution moved forward. Are you sure it's not a bug from the loss functions/ metric functions? I am using a multi-output model and during the first time that I read this, I thought that it could be due to the loss function defined within this repository. Normally, you provide a loss function to every output and then keras sums up all the losses from every output to calculate a mean loss. I don't know if this repository changed this functionality or affected it somehow.

**Comment by ntelo007** [comment]
I realized that the IoU Metric receives the wrong prediction shapes. Do you know why this is happening?
