### ISSUE TITLE
multi-class visualize problem

### ISSUE THREAD

**Issue by J0117** [qubvel/segmentation_models#317]
Hi, my dataset have 13classes include background
and model.predict shape is [1,384,480,13]
how can i visualize it on one image?

**Comment by J0117** [comment]
+
Traceback (most recent call last):
  File "C:/Users/SDR/Desktop/segmentation_models-master/train.py", line 427, in <module>
    pr_mask=pr_mask.squeeze(),
  File "C:/Users/SDR/Desktop/segmentation_models-master/train.py", line 32, in visualize
    plt.imshow(image)
  File "C:\Anaconda3\envs\s_m\lib\site-packages\matplotlib\pyplot.py", line 2684, in imshow
    None else {}), **kwargs)
  File "C:\Anaconda3\envs\s_m\lib\site-packages\matplotlib\__init__.py", line 1599, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\Anaconda3\envs\s_m\lib\site-packages\matplotlib\cbook\deprecation.py", line 369, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda3\envs\s_m\lib\site-packages\matplotlib\cbook\deprecation.py", line 369, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda3\envs\s_m\lib\site-packages\matplotlib\axes\_axes.py", line 5679, in imshow
    im.set_data(X)
  File "C:\Anaconda3\envs\s_m\lib\site-packages\matplotlib\image.py", line 690, in set_data
    .format(self._A.shape))
TypeError: Invalid shape (384, 480, 13) for image data

**Comment by VladislavAD** [comment]
Matplotlib can't handle 13 channels image. You need to assign color to each class and then paint them on one RGB image.
You can try something like this:
```
colors = [(255,0,0),(0,255,0)] # etc, add 13 colors
out_image = np.zeros_like(original_rgb_image)
for i in range(classes):
    class_mask = image[...,i] # get the layer of class
    class_mask = np.stack((class_mask * colors[i][0], class_mask * colors[i][1],class_mask * colors[i][2]), axis=-1)
    # you can simply add values but I don't use this approach with multiple classes
    out_image = out_image + class_mask
    # so if the above doesn't work you can use opencv addWeighted
    out_image = cv2.addWeighted(out_image ,1.0,class_mask,0.7,0)
# now you can plt.imshow(out_image)
```
Also you can place copy of original image into out_image and get classes painted over original

**Comment by JordanMakesMaps** [comment]
Another option is to overlay the entire mask on the class by changing the alpha:

```python
# turns the 13-channel mask into a 1-channel image
mask = np.argmax(y_pred, axis = 2)

plt.imshow(image)
plt.imshow(mask, alpha = .65)
plt.savefig(arr = mask, fname = "results.png")
plt.show()
```
or like @VladislavAD, is you only want to display a single class over the image:
```python
plt.imshow(image)
plt.imshow(y_pred[:, :, class_index], alpha = .65)
plt.show()
```

**Comment by J0117** [comment]
thanks :)
