### ISSUE TITLE
ValueError: Unknown loss function:binary_crossentropy_plus_jaccard_loss while loading saved model

### ISSUE THREAD

**Issue by bhomaidan1990** [qubvel/segmentation_models#335]
I have trained a model using Keras and SM, when I tried to load the model for prediction, I have got the following Error: `Traceback (most recent call last):
  File "D:\Saudi_CV\Vibot\Smester_2\2_Medical Image analysis\Project_2020\DL_Project\My_Project\EXE\Nifti_GUI.py", line 394, in setExistingFile
    prediction('temporary')
  File "D:\Saudi_CV\Vibot\Smester_2\2_Medical Image analysis\Project_2020\DL_Project\My_Project\EXE\predict.py", line 17, in prediction
    model = tf.keras.models.load_model("ResNet_34_Aug.h5")
  File "F:\Download_2019\Anaconda3\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "F:\Download_2019\Anaconda3\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 184, in load_model_from_hdf5
    training_config, custom_objects))
  File "F:\Download_2019\Anaconda3\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "F:\Download_2019\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 409, in compile
    self.loss, self.output_names)
  File "F:\Download_2019\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_utils.py", line 1447, in prepare_loss_functions
    loss_functions = [get_loss_function(loss) for _ in output_names]
  File "F:\Download_2019\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_utils.py", line 1447, in <listcomp>
    loss_functions = [get_loss_function(loss) for _ in output_names]
  File "F:\Download_2019\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_utils.py", line 1181, in get_loss_function
    loss_fn = losses.get(loss)
  File "F:\Download_2019\Anaconda3\lib\site-packages\tensorflow_core\python\keras\losses.py", line 1184, in get
    return deserialize(identifier)
  File "F:\Download_2019\Anaconda3\lib\site-packages\tensorflow_core\python\keras\losses.py", line 1175, in deserialize
    printable_module_name='loss function')
  File "F:\Download_2019\Anaconda3\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 322, in deserialize_keras_object
    raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
ValueError: Unknown loss function:binary_crossentropy_plus_jaccard_loss
[Finished in 11.3s with exit code 3221226505]` and the code is :

```
import os
import tensorflow as tf
from segmentation_models.losses import bce_jaccard_loss
from segmentation_models.metrics import iou_score

if(tf.test.is_gpu_available(cuda_only=True)):
    os.environ['CUDA_VISIBLE_DEVICES'] = '0'

model = tf.keras.models.load_model("ResNet_34_Aug.h5")
```

**Comment by bhomaidan1990** [comment]
I have recompiled it using:
`model = tf.keras.models.load_model("ResNet_34_Aug.h5",compile=False)
import segmentation_models as sm
model.compile( 'Adam',
    loss=sm.losses.bce_jaccard_loss,
    metrics=[sm.metrics.iou_score])`
