### ISSUE TITLE
Weird problem with metrics

### ISSUE THREAD

**Issue by EtagiBI** [qubvel/segmentation_models#336]
Hello,
I'm trying to reproduce [this example](https://github.com/qubvel/segmentation_models/blob/master/examples/binary%20segmentation%20(camvid).ipynb) using Tensorflow 1.15. I'm using `tk.keras` module instead of `keras`, but their methods should be identical. When I run training I get a following error:
```
Traceback (most recent call last):
  File "E:/qubvel2020/original.py", line 308, in <module>
    validation_steps=len(valid_dataloader),
  File "C:\Users\E-soft\Anaconda3\envs\qubvel2020\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\Users\E-soft\Anaconda3\envs\qubvel2020\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py", line 265, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "C:\Users\E-soft\Anaconda3\envs\qubvel2020\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1017, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "C:\Users\E-soft\Anaconda3\envs\qubvel2020\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "C:\Users\E-soft\Anaconda3\envs\qubvel2020\lib\site-packages\tensorflow_core\python\client\session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Invalid reduction dimension (0 for input with 0 dimension(s)
	 [[{{node metrics/f1-score/Sum_2}}]]
	 [[loss/mul/_4817]]
  (1) Invalid argument: Invalid reduction dimension (0 for input with 0 dimension(s)
	 [[{{node metrics/f1-score/Sum_2}}]]
0 successful operations.
0 derived errors ignored.

Process finished with exit code 1
```
When I remove F1 Score from metrics, I get another error complaining about IOU Score:
```
Traceback (most recent call last):
  File "E:/qubvel2020/original.py", line 308, in <module>
    validation_steps=len(valid_dataloader),
  File "C:\Users\E-soft\Anaconda3\envs\qubvel2020\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\Users\E-soft\Anaconda3\envs\qubvel2020\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py", line 265, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "C:\Users\E-soft\Anaconda3\envs\qubvel2020\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1017, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "C:\Users\E-soft\Anaconda3\envs\qubvel2020\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "C:\Users\E-soft\Anaconda3\envs\qubvel2020\lib\site-packages\tensorflow_core\python\client\session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Invalid reduction dimension (0 for input with 0 dimension(s)
	 [[{{node loss/sigmoid_loss/Sum_2}}]]
	 [[metrics/iou_score/Identity/_4807]]
  (1) Invalid argument: Invalid reduction dimension (0 for input with 0 dimension(s)
	 [[{{node loss/sigmoid_loss/Sum_2}}]]
0 successful operations.
0 derived errors ignored.

Process finished with exit code 1
```
Am I missing something? Should I switch to `keras`?

**Comment by EtagiBI** [comment]
Works fine with native `keras`. What a pity that even old versions of tf.keras aren't fully supported.

**Comment by elliestath** [comment]
I have the same problem even with native keras... is there a solution?
